parameters:
    dark_redis_list.list_manager.class: Dark\RedisListBundle\Manager\ListManager
    dark_redis_list.manager.class: Dark\RedisListBundle\Manager\Manager
    dark_redis_list.pagination.class: Dark\RedisListBundle\Pagination\Pagination
    dark_redis_list.Collector.single.class: Dark\RedisListBundle\Collector\Single
    dark_redis_list.Collector.pieces.class: Dark\RedisListBundle\Collector\Pieces

services:
     predis_client:
         alias: snc_redis.default_client

     dark_redis_list.list_manager:
        class: %dark_redis_list.list_manager.class%
        arguments:
            - "@predis_client"

     dark_redis_list.manager:
        class: %dark_redis_list.manager.class%
        arguments:
            - "@predis_client"

     dark_redis_list.pagination:
        class: %dark_redis_list.pagination.class%
        scope: request
        arguments:
            - "@predis_client"
            - "@dark_redis_list.collector"
            - "@templating"
            - "@request"
            - %dark_redis_list.template%

     dark_redis_list.Collector.single:
        class: %dark_redis_list.collector.single.class%
        arguments:
            - @doctrine.orm.entity_manager
            - %dark_redis_list.time%

     dark_redis_list.Collector.pieces:
        class: %dark_redis_list.collector.pieces.class%
        arguments:
            - "@doctrine.orm.entity_manager"
            - %dark_redis_list.time%